pbi:
  defaults:
    fileserver: "http://localhost:8081"
  
  dashboards:
    - id: 1_test
      display-name: test1
      description: Development Version of Application
      group-id: "f3bcc1ec-3b25-463e-b026-12b0d37b1e1b"
      report-id: "d6440ccd-6cf3-46b0-a0d0-026708c46819"
      do-not-display: noooo
      access-groups: ["user1"]
    
    - id: 2_test
      display-name: test2
      description: Development Version of the Application
      report-id: "f3bcc1ec-3b25-463e-b026-12b0d37b1e1b"
      group-id: "d6440ccd-6cf3-46b0-a0d0-026708c46819"
      access-groups: ["user2"]


  # dashboards:
  #   - id: 1_test
  #     display-name: test1
  #     description: Development Version of Application
  #     access-groups: ["user1"]
    
  #   - id: 2_test
  #     display-name: test2
  #     description: Development Version of the Application
  #     access-groups: ["user2"]