proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8081
  authentication: openid
  admin-groups: admin
  user-encrypt-key: whatever
  openid:
    auth-url: https://login.microsoftonline.com/f985d4e6-bf91-4342-a3b7-86318ce6ac7d/oauth2/authorize
    token-url: https://login.microsoftonline.com/f985d4e6-bf91-4342-a3b7-86318ce6ac7d/oauth2/token
    jwks-url: https://login.microsoftonline.com/f985d4e6-bf91-4342-a3b7-86318ce6ac7d/discovery/v2.0/keys
    # userinfo-url: https://sso-int.mercedes-benz.com/idp/userinfo.openid
    client-id: bbb351a4-7dcc-4215-bb59-ecdec7e6f144
    client-secret: 0By8Q~BTALm81GiepDpEH5gpiqoc_KdwwXSdtaMl
    username-attribute: email
    # acr-value: gas:strong
    scopes: ["email", "openid", "profile"]
    roles-claim: roles


  
  # authentication: simple
  # admin-groups: admin
  # user-encrypt-key: 1234
  # Example: 'simple' authentication configuration
  users:
  - name: user
    password: password
    groups: user
  - name: admin
    password: password
    groups: admin
  - name: developer
    password: password
    groups: admin
    # Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [admin, scientists, mathematicians]
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: scientists

logging:
  file:
    shinyproxy.log
  level:
    root: INFO #DEBUG
    org.springframework.security: DEBUG
spring:
  profiles:
    include:
      - pbi